[build]
  # 👇 change this to the folder that actually contains package.json, index.html, src/
  base = "Suite46"     
  command  = "npm run build"
  publish  = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
